name: Automatic PR Merger

on:
  push: {} # update PR when base branch is updated

jobs:
  # thats's all. single step is needed - if PR is mergeable according to
  # branch protection rules it will be merged automatically
  mergepal:
    runs-on: ubuntu-latest
    if: github.repository == 'RasaHQ/rasa'

    steps:
      - uses: actions/checkout@v3
      - uses: rasahq/update-pr-branch@35a3af76b9d3fc93e40a159921a34e36ca486529
        with:
          token: ${{ secrets.RASABOT_AUTOMERGE_GITHUB_TOKEN }}
          # required parameter by original action - 
          # check is already done through protected branches so not needed for us
          required_approval_count: 0
          # update branch despite failing check runs
          require_passed_checks: false
